.PHONY: clean All

All:
	@echo "----------Building project:[ Uebung1 - Debug ]----------"
	@cd "Uebung1" && $(MAKE) -f  "Uebung1.mk"
clean:
	@echo "----------Cleaning project:[ Uebung1 - Debug ]----------"
	@cd "Uebung1" && $(MAKE) -f  "Uebung1.mk" clean
